name: 'Render File'
description: 'Render files in the folder with yml/yaml extensions'
author: 'Furkan Tasbasi'
inputs:
  target-folder:
    description: 'Target folder to change files in it.'
    required: true
  secrets-context:
    description: 'Secret context of the current workflow.'
    required: false
  variables-context:
    description: 'Variable context of the current workflow.'
    required: false
branding:
  icon: check-square
  color: purple
runs:
  using: 'node20'
  main: 'index.js'
