name: 'Render File'
description: 'Render files in the folder with yml/yaml extensions'
author: 'Furkan Tasbasi'
inputs:
  file:
    description: 'Target is file or not. Default false (folder)'
    required: true
  target:
    description: 'Target folder/file to change file(s) in it.'
    required: true
  secrets-context:
    description: 'Secret context of the current workflow.'
    required: false
  variables-context:
    description: 'Variable context of the current workflow.'
    required: false
branding:
  icon: check-square
  color: purple
runs:
  using: 'node20'
  main: 'index.js'
