name: 'Update Environment Files'
description: 'A GitHub Action to update environment files based on secrets and variables.'
branding:
  icon: 'refresh-cw'  # Replace this with an appropriate icon from https://primer.style/octicons/
  color: 'gray-dark'  # Choose a color that represents your action

inputs:
  secrets_context:
    description: 'Secrets context JSON'
    required: false

  vars_context:
    description: 'Variables context JSON'
    required: false

  target_folder:
    description: 'Folder to render all files in'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secrets_context }}
    - ${{ inputs.vars_context }}
    - ${{ inputs.target_folder }}
