name: 'Render File'
description: 'Render files in the folder'
inputs:
  target-folder:
    description: 'Target folder to change files in it.'
    required: true
  secrets-context:
    description: 'Secret context of the current workflow.'
    required: true
  variables-context:
    description: 'Variable context of the current workflow.'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
